import Head from 'next/head'
import SiderBr from '../components/SiderBr'

export default function Home() {
  return (
    <div>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

        <main>
          <SiderBr />
        </main>
    </div>
  )
}

